# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97e19199c884c275aa234720c5ce8838"
application_url = "https://example.com"
embedded = true
name = "Dynamic Product Slider"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_app_proxy"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "/apps/dynamic-product-slider"
prefix = "apps"
subpath = "dynamic-product-slider"
